### PR TITLE
Feature/update leaf tag

### PR DESCRIPTION
**Pull request by mauran**

### CODE REVIEW

**Comment by mauran** [comment]
So i updated the menu to only show 11 page items.

image

Result if there is only one page

image

Result if amount of pages is less than 11

image

**Comment by steffendsommer** [comment]
@mauran thanks for looking into this issue. Do you mind posting screenshots or describing some more cases? E.g. what happens when there are more than 11 pages and you're on page 1 or the last page? Or if there's a lot of pages and you're on the most middle page?

Also, there's some indentation which got changed together with this PR.

**Comment by mauran** [comment]
More than 11 pages and on page 1
image

I found some bugs when going to last page, etc. I'll fix them and update the indentation. 👍

**Comment by mauran** [comment]
@steffendsommer 

Crunched some bugs. 

image
When you're in the middle of a pagination 

image
When you're near some of the last pages 

image

When you're on the last page

**Comment by steffendsommer** [comment]
Some feedback when somebody picks this up:

- I think it makes sense to indicate that more pages exists than shown in the paginator (see screenshot of when you're in the middle of pagination). This should probably apply to each direction.
- We could consider adding first/previous and next/last controls to make it easier to jump to the first and last page in the pagination.
- It's hard to see from the screenshots, but we should make sure indicate when controls are not functional (e.g. next/last when on last page)

**Review by steffendsommer — CHANGES_REQUESTED** [review]
See my other comment for more details.

**Comment by steffendsommer** [comment]
Closing as this will be addressed with the Vapor 3 version (https://github.com/nodes-vapor/paginator/pull/58)

**Pull request closed without merging**
