### PR TITLE
Changed meta keys to camel case

### PR DESCRIPTION
**Pull request by rasmusebbesen**

### CODE REVIEW

**Comment by TimC-BBC** [comment]
Is there a particular justification for this? Some databases (looking at you Postgres) convert all database column names to lowercase so most `makeNode` functions in Vapor seem to have become `snake_case` which seems to be becoming a convention in Node. IMO it would make sense to keep it the same - but I'm only talking from my experience and what I've seen

**Comment by 0xTim** [comment]
Is there a particular justification for this? Some databases (looking at you Postgres) convert all database column names to lowercase so most `makeNode` functions in Vapor seem to have become `snake_case` which seems to be becoming a convention in Node. IMO it would make sense to keep it the same - but I'm only talking from my experience and what I've seen

**Comment by rasmusebbesen** [comment]
I think it will be a matter of taste. Rumors has it, that In vapor 2 they will add a setting for casing in the database layer, so I guess we should use that for these column names as well.

**Comment by steffendsommer** [comment]
We're now respecting the strategy coming from Fluent (being snake- or camel case): https://github.com/nodes-vapor/paginator/pull/29. Closing this issue.

**Pull request closed without merging**
